FinalProject/force-app/main/default/objects/Opportunity/fields/EndProject__c.field-meta.xml
<CustomField>
    <fullName>EndProject__c</fullName>
    <label>EndProject</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

FinalProject/force-app/main/default/objects/Opportunity/fields/PM__c.field-meta.xml
<CustomField>
    <fullName>PM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Project Manager</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

FinalProject/force-app/main/default/objects/Opportunity/fields/StartProject__c.field-meta.xml
<CustomField>
    <fullName>StartProject__c</fullName>
    <label>StartProject</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

FinalProject/force-app/main/default/objects/OpportunityLineItem__c/OpportunityLineItem__c.object-meta.xml
<CustomObject>
    <label>OpportunityLineItem</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OpportunityLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FinalProject/force-app/main/default/objects/OpportunityLineItem__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Assignament Project Roles</relationshipLabel>
    <relationshipName>OpportunityLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FinalProject/force-app/main/default/objects/OpportunityLineItem__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Roles</valueSetName>
    </valueSet>
</CustomField>

FinalProject/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FinalProject/force-app/main/default/objects/Project__c/fields/EndProject__c.field-meta.xml
<CustomField>
    <fullName>EndProject__c</fullName>
    <label>EndProject</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

FinalProject/force-app/main/default/objects/Project__c/fields/PM__c.field-meta.xml
<CustomField>
    <fullName>PM__c</fullName>
    <label>PM</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

FinalProject/force-app/main/default/objects/Project__c/fields/StartProject__c.field-meta.xml
<CustomField>
    <fullName>StartProject__c</fullName>
    <label>StartProject</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

FinalProject/force-app/main/default/objects/ProjectLineItem__c/ProjectLineItem__c.object-meta.xml
<CustomObject>
    <label>ProjectLineItem</label>
    <nameField>
        <label>Project Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProjectLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FinalProject/force-app/main/default/objects/ProjectLineItem__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Admin Roles</relationshipLabel>
    <relationshipName>ProjectLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FinalProject/force-app/main/default/objects/ProjectResource__c/ProjectResource__c.object-meta.xml
<CustomObject>
    <label>ProjectResource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProjectResources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FinalProject/force-app/main/default/objects/ProjectResource__c/fields/EndDateResource__c.field-meta.xml
<CustomField>
    <fullName>EndDateResource__c</fullName>
    <label>EndDateResource</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

FinalProject/force-app/main/default/objects/ProjectResource__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>ProjectLineItem__r.Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

FinalProject/force-app/main/default/objects/ProjectResource__c/fields/ProjectLineItem__c.field-meta.xml
<CustomField>
    <fullName>ProjectLineItem__c</fullName>
    <label>ProjectLineItem</label>
    <referenceTo>ProjectLineItem__c</referenceTo>
    <relationshipLabel>Resources Assignment</relationshipLabel>
    <relationshipName>ProjectResources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FinalProject/force-app/main/default/objects/ProjectResource__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ProjectResources</relationshipName>
    <type>Lookup</type>
</CustomField>

FinalProject/force-app/main/default/objects/ProjectResource__c/fields/StartDateResource__c.field-meta.xml
<CustomField>
    <fullName>StartDateResource__c</fullName>
    <label>StartDateResource</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

FinalProject/force-app/main/default/globalValueSets/Roles.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Developer</fullName>
    </customValue>
    <customValue>
        <fullName>Project Manager</fullName>
    </customValue>
    <masterLabel>Roles</masterLabel>
</GlobalValueSet>

FinalProject/force-app/main/default/classes/ProjectResourceTriggerTest.cls
@isTest
public with sharing class ProjectResourceTriggerTest {

    private static String role ='Developer';
    private static User dev =[SELECT Id, LastName, UserRole.Name FROM User WHERE UserRole.Name = 'Developer' LIMIT 1 ];

    private static Opportunity newOpp (Id pm){
        Opportunity newOpp = new Opportunity (
            Name= 'Opp Test',
            CloseDate= System.today(),
            StartProject__c= System.today(),
            EndProject__c = System.today().addDays(30),
            PM__c= pm,
            StageName= 'Negotiation/Review'
        );
        return newOpp;
    }

    private static OpportunityLineItem__c newOppLineItem(Id oppId, String role){

        OpportunityLineItem__c oppLineItem = new OpportunityLineItem__c(
            Name = role,
            Opportunity__c = oppId,
            Role__c =role,
            QuantityHours__c = 24,
            Amount__c = 500
        );
        return oppLineItem;
    }

    private static ProjectResource__c newPR (Id PLiID, Date startDate ,Date endDate, Id resourceId){
        ProjectResource__c PR = new ProjectResource__c(
            Name = '',
            ProjectLineItem__c = PLiId,
            StartDateResource__c = startDate,
            EndDateResource__c = endDate,
            Resource__c = resourceId
            );
        return PR;
    }

    @isTest

    private static void testProjectResourceTrigger(){
        //SET UP 
        User pm = [SELECT Id, Name FROM User WHERE UserRole.Name = 'Project Manager' LIMIT 1];

        Opportunity opp = newOpp(pm.Id);
        insert opp;
        Id oppId = opp.Id;

        OpportunityLineItem__c oppLI = newOppLineItem(oppId, role);       
        insert oppLI;

        opp.StageName = 'Closed Won';
        update opp;
		
        //TEST POSITIVE
        Project__c project =[SELECT Id, Name, Opportunity__c FROM Project__c ];  

        ProjectLineItem__c PLI =[SELECT Id, Project__c FROM ProjectLineItem__c WHERE Project__c =: project.Id];
        
        ProjectResource__c PR1 = newPR(PLI.Id, System.today(), System.today().addDays(10),dev.Id);
        insert PR1;
           
        ProjectResource__c PR2 = newPR(PLI.Id, System.today().addDays(11), System.today().addDays(20),dev.Id);
        insert PR2;
		
        //TEST NEGATIVE
        ProjectResource__c PR3 = newPR(PLI.Id, System.today(), System.today().addMonths(2),dev.Id);
        
        try {
            insert PR3;
        } catch (DmlException e) {
            //Assert Error Message
            System.assert( e.getMessage().contains('Insert failed. First exception on ' +
                'row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, ' +
                'The dates assigned do not correspond to the dates of the project: []'), 
                e.getMessage() );

                //Assert Status Code
                System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION' , 
                                 e.getDmlStatusCode(0) );
        } 

        ProjectResource__c PR4 = newPR(PLI.Id, System.today(), System.today().addDays(10),dev.Id);

        try {
            insert PR4;
        } catch (DmlException e) {
            //Assert Error Message
            System.assert( e.getMessage().contains('Insert failed. First exception on ' +
                'row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, ' +
                'The resource '+ dev.LastName +' is not available on these Dates: []'), 
                e.getMessage() );

                //Assert Status Code
                System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION' , 
                                 e.getDmlStatusCode(0) );
        } 


        List<ProjectResource__c> ProjectResourceCreated = [SELECT Id, Name FROM ProjectResource__c];
		
        //ASSERT POSITIVE
        System.assertEquals(2, ProjectResourceCreated.size());

    }
}