FinalProject/force-app/main/default/objects/Opportunity/fields/EndProject__c.field-meta.xml
<CustomField>
    <fullName>EndProject__c</fullName>
    <label>EndProject</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

FinalProject/force-app/main/default/objects/Opportunity/fields/PM__c.field-meta.xml
<CustomField>
    <fullName>PM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Project Manager</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

FinalProject/force-app/main/default/objects/Opportunity/fields/StartProject__c.field-meta.xml
<CustomField>
    <fullName>StartProject__c</fullName>
    <label>StartProject</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

FinalProject/force-app/main/default/objects/OpportunityLineItem__c/OpportunityLineItem__c.object-meta.xml
<CustomObject>
    <label>OpportunityLineItem</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OpportunityLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FinalProject/force-app/main/default/objects/OpportunityLineItem__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Assignament Project Roles</relationshipLabel>
    <relationshipName>OpportunityLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FinalProject/force-app/main/default/objects/OpportunityLineItem__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Roles</valueSetName>
    </valueSet>
</CustomField>

FinalProject/force-app/main/default/objects/ProjectLineItem__c/ProjectLineItem__c.object-meta.xml
<CustomObject>
    <label>ProjectLineItem</label>
    <nameField>
        <label>Project Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProjectLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FinalProject/force-app/main/default/objects/ProjectResource__c/ProjectResource__c.object-meta.xml
<CustomObject>
    <label>ProjectResource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProjectResources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FinalProject/force-app/main/default/objects/ProjectResource__c/fields/EndDateResource__c.field-meta.xml
<CustomField>
    <fullName>EndDateResource__c</fullName>
    <label>EndDateResource</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

FinalProject/force-app/main/default/objects/ProjectResource__c/fields/ProjectLineItem__c.field-meta.xml
<CustomField>
    <fullName>ProjectLineItem__c</fullName>
    <label>ProjectLineItem</label>
    <referenceTo>ProjectLineItem__c</referenceTo>
    <relationshipLabel>Resources Assignment</relationshipLabel>
    <relationshipName>ProjectResources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FinalProject/force-app/main/default/objects/ProjectResource__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ProjectResources</relationshipName>
    <type>Lookup</type>
</CustomField>

FinalProject/force-app/main/default/objects/ProjectResource__c/fields/StartDateResource__c.field-meta.xml
<CustomField>
    <fullName>StartDateResource__c</fullName>
    <label>StartDateResource</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

FinalProject/force-app/main/default/globalValueSets/Roles.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Developer</fullName>
    </customValue>
    <customValue>
        <fullName>Project Manager</fullName>
    </customValue>
    <masterLabel>Roles</masterLabel>
</GlobalValueSet>

FinalProject/force-app/main/default/classes/ProjectDataServiceTest.cls
@isTest
public with sharing class ProjectDataServiceTest {
    
    private static Opportunity newOpp (Id pm){
        Opportunity newOpp = new Opportunity (
            Name= 'Opp Test',
            CloseDate= System.today(),
            StartProject__c= System.today(),
            EndProject__c = System.today().addDays(30),
            PM__c= pm,
            StageName= 'Negotiation/Review'
        );
        return newOpp;
    }

    private static OpportunityLineItem__c newOppLineItem(Id oppId, String role){

        OpportunityLineItem__c oppLineItem = new OpportunityLineItem__c(
            Name = role,
            Opportunity__c = oppId,
            Role__c =role,
            QuantityHours__c = 24,
            Amount__c = 500
        );
        return oppLineItem;
    }

    private static ProjectResource__c newPR (Id PLiID, Date startDate ,Date endDate, Id resourceId){
        ProjectResource__c PR = new ProjectResource__c(
            Name = '',
            ProjectLineItem__c = PLiId,
            StartDateResource__c = startDate,
            EndDateResource__c = endDate,
            Resource__c = resourceId
            );
        return PR;
    }

    @isTest

    private static void testProjectDataService(){
        //SET UP
        List<User> userList =[SELECT Id, Name, UserRole.Name FROM USER WHERE UserRole.Name = 'Developer'];

        
    }
}