FinalProject/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FinalProject/force-app/main/default/objects/Project__c/fields/ActualTotalAmount__c.field-meta.xml
<CustomField>
    <fullName>ActualTotalAmount__c</fullName>
    <formula>AmountOpp__c - AmountEstimated__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ActualTotalAmount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

FinalProject/force-app/main/default/objects/Project__c/fields/EndProject__c.field-meta.xml
<CustomField>
    <fullName>EndProject__c</fullName>
    <label>EndProject</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

FinalProject/force-app/main/default/objects/Project__c/fields/StartProject__c.field-meta.xml
<CustomField>
    <fullName>StartProject__c</fullName>
    <label>StartProject</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

FinalProject/force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Kickoff</fullName>
                <default>true</default>
                <label>Pre-Kickoff</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FinalProject/force-app/main/default/objects/ProjectLineItem__c/ProjectLineItem__c.object-meta.xml
<CustomObject>
    <label>ProjectLineItem</label>
    <nameField>
        <label>Project Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProjectLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FinalProject/force-app/main/default/objects/ProjectLineItem__c/fields/ActualTotalHours__c.field-meta.xml
<CustomField>
    <fullName>ActualTotalHours__c</fullName>
    <description>Horas totales a cubrir menos las horas asignadas hasta el momento</description>
    <formula>QuantityHours__c -  AssignedHours__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ActualTotalHours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

FinalProject/force-app/main/default/objects/ProjectLineItem__c/fields/AssignedHours__c.field-meta.xml
<CustomField>
    <fullName>AssignedHours__c</fullName>
    <label>AssignedHours</label>
    <summarizedField>ProjectResource__c.HoursAssigned__c</summarizedField>
    <summaryForeignKey>ProjectResource__c.ProjectLineItem__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

FinalProject/force-app/main/default/objects/ProjectLineItem__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Admin Roles</relationshipLabel>
    <relationshipName>ProjectLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FinalProject/force-app/main/default/objects/ProjectResource__c/ProjectResource__c.object-meta.xml
<CustomObject>
    <label>ProjectResource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProjectResources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FinalProject/force-app/main/default/objects/ProjectResource__c/fields/EndDateResource__c.field-meta.xml
<CustomField>
    <fullName>EndDateResource__c</fullName>
    <label>EndDateResource</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

FinalProject/force-app/main/default/objects/ProjectResource__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>ProjectLineItem__r.Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

FinalProject/force-app/main/default/objects/ProjectResource__c/fields/ProjectLineItem__c.field-meta.xml
<CustomField>
    <fullName>ProjectLineItem__c</fullName>
    <label>ProjectLineItem</label>
    <referenceTo>ProjectLineItem__c</referenceTo>
    <relationshipLabel>Resources Assignment</relationshipLabel>
    <relationshipName>ProjectResources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FinalProject/force-app/main/default/objects/ProjectResource__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ProjectResources</relationshipName>
    <type>Lookup</type>
</CustomField>

FinalProject/force-app/main/default/objects/ProjectResource__c/fields/StartDateResource__c.field-meta.xml
<CustomField>
    <fullName>StartDateResource__c</fullName>
    <label>StartDateResource</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

FinalProject/force-app/main/default/objects/TaskProject__c/TaskProject__c.object-meta.xml
<CustomObject>
    <label>TaskProject</label>
    <nameField>
        <label>TaskProject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FinalProject/force-app/main/default/objects/TaskProject__c/fields/EndTask__c.field-meta.xml
<CustomField>
    <fullName>EndTask__c</fullName>
    <label>EndTask</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

FinalProject/force-app/main/default/objects/TaskProject__c/fields/EstimatedHours__c.field-meta.xml
<CustomField>
    <fullName>EstimatedHours__c</fullName>
    <formula>(((5 * ( FLOOR( ( EndTask__c  - DATE( 1900, 1, 8) ) / 7 ) ) + MIN( 5, MOD( EndTask__c - DATE( 1900, 1, 8), 7 ) ) )
-
(5 * ( FLOOR( ( StartTask__c  - DATE( 1900, 1, 8) ) / 7 ) ) + MIN( 5, MOD( StartTask__c - DATE( 1900, 1, 8), 7 ) ) )) + 1) * 8</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EstimatedHours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FinalProject/force-app/main/default/objects/TaskProject__c/fields/InProgress__c.field-meta.xml
<CustomField>
    <fullName>InProgress__c</fullName>
    <formula>IF(ISPICKVAL(Status__c,&apos;In Progress&apos;), true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>InProgress</label>
    <type>Checkbox</type>
</CustomField>

FinalProject/force-app/main/default/objects/TaskProject__c/fields/InsertHs__c.field-meta.xml
<CustomField>
    <fullName>InsertHs__c</fullName>
    <label>InsertHs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FinalProject/force-app/main/default/objects/TaskProject__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>CASESAFEID(ProjectResource__r.ProjectLineItem__r.Project__r.Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

FinalProject/force-app/main/default/objects/TaskProject__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <formula>ProjectResource__r.ProjectLineItem__r.Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Name</label>
    <type>Text</type>
</CustomField>

FinalProject/force-app/main/default/objects/TaskProject__c/fields/ProjectResource__c.field-meta.xml
<CustomField>
    <fullName>ProjectResource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ProjectResource</label>
    <referenceTo>ProjectResource__c</referenceTo>
    <relationshipLabel>TaskProjects</relationshipLabel>
    <relationshipName>TaskProjects</relationshipName>
    <type>Lookup</type>
</CustomField>

FinalProject/force-app/main/default/objects/TaskProject__c/fields/RegisterHours__c.field-meta.xml
<CustomField>
    <fullName>RegisterHours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RegisterHours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FinalProject/force-app/main/default/objects/TaskProject__c/fields/StartTask__c.field-meta.xml
<CustomField>
    <fullName>StartTask__c</fullName>
    <label>StartTask</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

FinalProject/force-app/main/default/objects/TaskProject__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FinalProject/force-app/main/default/objects/User/fields/RatePerHour__c.field-meta.xml
<CustomField>
    <fullName>RatePerHour__c</fullName>
    <label>RatePerHour</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

FinalProject/force-app/main/default/classes/ProjectDataService.cls
public with sharing class ProjectDataService {
   
    //Obtiene los projectLineItem de un proyecto 
    @AuraEnabled(cacheable = true)
    public static List<ProjectLineItem__c> getRolesByProject (String projectId){
        return [SELECT Id, Role__c, QuantityHours__c, Project__c, AssignedHours__c,Project__r.ActualTotalAmount__c, ActualTotalHours__c FROM ProjectLineItem__c WHERE Project__c =: projectId];
    }
    
    //Obtiene todos los Recursos asignados a un determinado proyecto
    @AuraEnabled(cacheable = true)
    public static List<Object> getProjectResource(String projectId){
        
        List<ProjectLineItem__c> PLI = [SELECT Id, Project__c FROM ProjectLineItem__c WHERE Project__c =: projectId];
        
        return [SELECT Name, StartDateResource__c, EndDateResource__c, ProjectLineItem__c FROM ProjectResource__c WHERE ProjectLineItem__c IN : PLI ];
    }

    //Obtiene los usuarios de 'x' Rol disponibles en las fechas del proyecto
    @AuraEnabled(cacheable = true)
    public static List<User> getUsersByRole (String role, String projectId){
        Boolean assign = true;
        //Buscamos en la DB el proyecto actual
        Project__c project =[SELECT Id, Name, StartProject__c, EndProject__c, ActualTotalAmount__c FROM Project__c WHERE Id =: projectId];
       
        Date startProject = project.StartProject__c;
        Date endProject = project.EndProject__c;
        
        //Buscamos en la DB todos los usuarios con un mismo rol disponibles para el proyecto
        List<User> usersListByRole =[SELECT Id, Name, UserRole.Name, RatePerHour__c, ( SELECT StartDateResource__c, EndDateResource__c, ProjectLineItem__r.Project__c FROM ProjectResources__r WHERE  (StartDateResource__c >=:startProject AND StartDateResource__c <=: endProject) OR (EndDateResource__c >=:startProject AND EndDateResource__c <=: endProject )) FROM User WHERE UserRole.Name =: role ];

        //Creamos una List para popular los usuarios disponibles para el proyecto
        List<User> availableUsers = new List<User>();
        //Filtramos los usuarios y populamos la lista
        for(User user : usersListByRole){
            if(user.ProjectResources__r.isEmpty()){
                availableUsers.add(user);
            } else {
                for(ProjectResource__c pr : user.ProjectResources__r){
                if(pr.ProjectLineItem__r.Project__c != project.Id){
                    assign = false;
                }
            }
            if(assign){
                availableUsers.add(user);
            }
            }
        }   
        return availableUsers;
    }  
    
    //Obtiene las tareas asignadas al Usuario logueado
    @AuraEnabled(cacheable = true)
    public static Map<String, List<TaskProject__c>> getTaskByUser (){
        List<TaskProject__c> tasksList = [SELECT Project_Name__c, InProgress__c, Name, Description__c, Status__c, EstimatedHours__c, RegisterHours__c, InsertHs__c, ProjectResource__r.Resource__c, Project__c, StartTask__c, EndTask__c FROM TaskProject__c WHERE OwnerId =: UserInfo.getUserId() AND Status__c != 'Completed' ORDER BY  StartTask__c, Status__c DESC];

        Map<String, List<TaskProject__c>> taskListByProjectMap = new Map<String, List<TaskProject__c>>();

        for(TaskProject__c tsk: tasksList){
            if(taskListByProjectMap.containsKey(tsk.Project_Name__c)){
                taskListByProjectMap.get(tsk.Project_Name__c).add(tsk);
            } else{
                taskListByProjectMap.put(tsk.Project_Name__c, new List<TaskProject__c>{tsk});
            }
        }

        return taskListByProjectMap;
    }
    
    //Crea en la DB la asignacion de los recursos provenientes del front
    @AuraEnabled
    public static void assignResource (List<ProjectResource__c> resourceToAssign){
     
        insert resourceToAssign;
    }
    
}